# Generated by Django 4.2.9 on 2024-02-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='limit',
            new_name='is_limit',
        ),
    ]
